// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxcTNxyXGOG2fNJ0EhH9ulPYXQshO0UcA',
    appId: '1:779346109460:web:97f2e8cd42945b519b7301',
    messagingSenderId: '779346109460',
    projectId: 'boilerplate-aaron-tech',
    authDomain: 'boilerplate-aaron-tech.firebaseapp.com',
    storageBucket: 'boilerplate-aaron-tech.appspot.com',
    measurementId: 'G-DGZJ8TLKG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKXo2tcww6Zt4G4ndxMELYsKrWvuX5VGI',
    appId: '1:779346109460:android:11b0bd1bdd7dd8629b7301',
    messagingSenderId: '779346109460',
    projectId: 'boilerplate-aaron-tech',
    storageBucket: 'boilerplate-aaron-tech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvlC92QkF6Cee5lnBjyaEG-Zv5lZbTYXw',
    appId: '1:779346109460:ios:43c1a3e120f0b4dd9b7301',
    messagingSenderId: '779346109460',
    projectId: 'boilerplate-aaron-tech',
    storageBucket: 'boilerplate-aaron-tech.appspot.com',
    iosBundleId: 'com.aarontech.boilerplate.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvlC92QkF6Cee5lnBjyaEG-Zv5lZbTYXw',
    appId: '1:779346109460:ios:7bfd57ccf7da1cbf9b7301',
    messagingSenderId: '779346109460',
    projectId: 'boilerplate-aaron-tech',
    storageBucket: 'boilerplate-aaron-tech.appspot.com',
    iosBundleId: 'com.aarontech.boilerplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxcTNxyXGOG2fNJ0EhH9ulPYXQshO0UcA',
    appId: '1:779346109460:web:d322392cd0a80e949b7301',
    messagingSenderId: '779346109460',
    projectId: 'boilerplate-aaron-tech',
    authDomain: 'boilerplate-aaron-tech.firebaseapp.com',
    storageBucket: 'boilerplate-aaron-tech.appspot.com',
    measurementId: 'G-FWBDJP3HJ4',
  );
}
